//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.SearchRowServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchRowServiceReference.ISearchRowService")]
    public interface ISearchRowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchRowService/SearchRow", ReplyAction="http://tempuri.org/ISearchRowService/SearchRowResponse")]
        WcfServiceLibrary.Contracts.SearchResultDto SearchRow(string query, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchRowService/SearchRow", ReplyAction="http://tempuri.org/ISearchRowService/SearchRowResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary.Contracts.SearchResultDto> SearchRowAsync(string query, int page);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchRowServiceChannel : WpfClient.SearchRowServiceReference.ISearchRowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchRowServiceClient : System.ServiceModel.ClientBase<WpfClient.SearchRowServiceReference.ISearchRowService>, WpfClient.SearchRowServiceReference.ISearchRowService {
        
        public SearchRowServiceClient() {
        }
        
        public SearchRowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchRowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchRowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchRowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceLibrary.Contracts.SearchResultDto SearchRow(string query, int page) {
            return base.Channel.SearchRow(query, page);
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary.Contracts.SearchResultDto> SearchRowAsync(string query, int page) {
            return base.Channel.SearchRowAsync(query, page);
        }
    }
}
